grafana:
  # 程序自身可访问的 grafna 地址，可以使用内网地址，只要本程序可以访问即可
  public_url: https://your-grafana.com
  # 在 Grafana 后台中创建一个服务账户，即可获得 token
  token: your-token
s3:
  region:
  bucket:
  public_url:
  endpoint_url:
  access_key_id:
  secret_access_key:
  addressing_style: virtual  # path / virtual
files:
  # 产生的临时文件保存天数，仅清理本地文件，S3文件请自行配置过期策略
  expiry_days: 2
openai:
  api_key: yourapikey
  base_url: