grafana:
  domain: your-domain
  tls: true
  token: your-token

# notifier 是一个示例，向你展示支持的发送程序如何配置
# 你也可以在这里写上配置，使用 yaml 锚点和引用的语法，
# 为常用的配置添加锚点，并在 job 中重复引用。
notifier:
  - &boss
    type: dingtalk_webhook
    config:
      webhook: example1.com
  - &team
    type: worktool
    config:
      robotid: your-robotid
      receiver:
        - chatgroup
        - Tom

job:
    - name:  # 人类可读命名，没有其他用途
      dashboard:
        - uid:    # dashboard uid
          query:  # 查询变量，例如 var-season=春天&var-status=All
          width:  # 宽度，对 png 和 pdf 生效
          type:   # 可选 png pdf
      panel:
        - dash_uid:    # dashboard uid
          uid:         # panel uid
          width:       # 宽度，对 png 和 pdf 生效
          type:        # 可选 png pdf csv xlsx
      cron:
        month:
      notifier: *boss

    - name:  # 人类可读命名，没有其他用途
      dashboard:
        - uid:    # dashboard uid
          query:  # 查询变量，例如 var-season=春天&var-status=All
          width:  # 宽度，对 png 和 pdf 生效
          type:   # 可选 png pdf
      panel:
        - dash_uid:    # dashboard uid
          uid:         # panel uid
          width:       # 宽度，对 png 和 pdf 生效
          type:        # 可选 png pdf csv xlsx
      schedule:
        every:    # 参考 Readme.md
        at_time:
        at_week:
      notifier: *team

