DingTalkWebhook:
  # 钉钉 WEBHOOK 机器人，只能发送文本和图片，文件只会以明文链接形式发送。
  # 无需更改默认的 uri 配置，从钉钉复制的 webhook 地址中，access_token
  # 等号后面的部分需要填写到 job.yaml 作为 receiver
  #
  # 在 job.yaml 中的使用方法：
  # notifier:
  #   type: DingTalkWebhook
  #   receiver:
  #     - access_token_1
  #     - access_token_2
  uri: https://oapi.dingtalk.com/robot/send

Gotify:
  # 只能发送文本和图片，文件只会以明文链接形式发送。
  # 无需更改默认的 uri 配置，token 需要填写到 job.yaml 作为 receiver
  #
  # 在 job.yaml 中的使用方法：
  # notifier:
  #   type: Gotify
  #   receiver:
  #     - token_1
  #     - token_2
  uri: https://your-domain/message

Worktool:
  # 一个第三方的微信及企微机器人，具体信息可见 https://worktool.apifox.cn/
  # 无需更改默认的 uri 配置，需要填写你的 robot_id
  #
  # 在 job.yaml 中的使用方法：
  # notifier:
  #   type: Worktool
  #   receiver:
  #     - 杰哥
  #     - 产品测试群
  uri: https://api.worktool.ymdyes.cn/wework/sendRawMessage
  robot_id: your_robot_id